'use client';

import { useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { rankHighlights, scoreReasons } from '../lib/domain/importance';
import { updateClinicWeights } from '../lib/domain/learning';
import { redactBeforeProvider } from '../lib/domain/redaction';
import { editEntry, revertEntry } from '../lib/domain/revisions';
import type { CareEntry, FeedbackAction, Highlight, HighlightCategory, Role } from '../lib/domain/models';

const dizzinessText = 'Patient reports episodes of dizziness since the medication adjustment last week. She believes she stopped metformin after the change.';
const hbaText = 'HbA1c has increased from 7.1% to 8.3%. Sarah clarified she has continued metformin 500 mg twice daily; the earlier AI statement was incomplete.';
const renalText = 'Renal function laboratory follow-up remains pending. Open for 12 days and assigned to Nurse Alice.';
const initialEntries: CareEntry[] = [
  { id:'e-aug24', type:'doctor_consult', label:'Doctor Consult', author:'Dr Marcus Lim', authorRole:'clinician', date:'Aug 24, 2026', time:'4:18 PM', title:'Diabetes review and treatment plan', content:hbaText, visibility:'patient', trust:'Clinician Confirmed', versions:[{id:'e-aug24-v1',version:1,content:'HbA1c has increased from 7.1% to 8.3%. Treatment plan: continue metformin 500 mg twice daily pending review.',actor:'Dr Marcus Lim',createdAt:'Aug 24 · 4:18 PM'},{id:'e-aug24-v2',version:2,content:hbaText,actor:'Dr Marcus Lim',createdAt:'Aug 25 · 2:32 PM'}] },
  { id:'e-aug23', type:'ai_patient_session_summary', label:'AI Patient Session', author:'Nightingale Scribe', authorRole:'system', date:'Aug 23, 2026', time:'8:04 PM', title:'Patient check-in before review', content:dizzinessText, visibility:'internal', trust:'Conflict Detected', ai:true, supersededBy:'e-aug24', versions:[{id:'e-aug23-v1',version:1,content:dizzinessText,actor:'Nightingale Scribe',createdAt:'Aug 23 · 8:04 PM'}] },
  { id:'e-aug13', type:'nurse_followup', label:'Nurse Follow-up', author:'Nurse Alice Wong', authorRole:'staff', date:'Aug 13, 2026', time:'11:20 AM', title:'Post-adjustment laboratory follow-up', content:renalText, visibility:'internal', versions:[{id:'e-aug13-v1',version:1,content:renalText,actor:'Nurse Alice Wong',createdAt:'Aug 13 · 11:20 AM'}] },
  { id:'e-feb06', type:'ai_doctor_consult_summary', label:'AI Scribe · Doctor Consult', author:'Nightingale Scribe', authorRole:'system', date:'Feb 06, 2026', time:'3:10 PM', title:'Routine diabetes review', content:'HbA1c measured at 7.3%. Blood pressure stable. Continue current medication and reinforce meal planning.', visibility:'internal', trust:'Clinician Confirmed', ai:true, decayTier:'summary', versions:[{id:'e-feb06-v1',version:1,content:'HbA1c measured at 7.3%. Blood pressure stable. Continue current medication and reinforce meal planning.',actor:'Nightingale Scribe',createdAt:'Feb 06 · 3:10 PM'}] },
  { id:'e-apr15', type:'doctor_consult', label:'Doctor Consult', author:'Dr Marcus Lim', authorRole:'clinician', date:'Apr 15, 2025', time:'9:35 AM', title:'Annual chronic care review', content:'HbA1c baseline 7.1%. Hypertension controlled. No dizziness or medication tolerance concerns reported.', visibility:'patient', trust:'Clinician Confirmed', decayTier:'compressed', versions:[{id:'e-apr15-v1',version:1,content:'HbA1c baseline 7.1%. Hypertension controlled. No dizziness or medication tolerance concerns reported.',actor:'Dr Marcus Lim',createdAt:'Apr 15 · 9:35 AM'}] },
];
const initialHighlights: Highlight[] = [
  { id:'h-hba',category:'lab_abnormality',title:'HbA1c worsening',detail:'7.1% → 8.3% since previous review',level:'Attention',sourceEntryId:'e-aug24',sourceVersionId:'e-aug24-v2',startOffset:hbaText.indexOf('HbA1c'),endOffset:hbaText.indexOf('8.3%')+4,sourceExcerpt:'HbA1c has increased from 7.1% to 8.3%',trust:'Clinician Confirmed',occurredAt:'Aug 24 · Doctor Consult',components:{risk:.7,unresolved:.2,recency:.85,clinicalChange:1,conflict:0,confirmation:1} },
  { id:'h-dizziness',category:'new_symptom',title:'Dizziness following medication change',detail:'Reported by patient 2 days ago',level:'Attention',sourceEntryId:'e-aug23',sourceVersionId:'e-aug23-v1',startOffset:dizzinessText.indexOf('dizziness'),endOffset:dizzinessText.indexOf('last week')+9,sourceExcerpt:'dizziness since the medication adjustment last week',trust:'AI Suggested',occurredAt:'Aug 23 · AI Patient Session',components:{risk:.7,unresolved:.7,recency:1,clinicalChange:1,conflict:.4,confirmation:0} },
  { id:'h-renal',category:'unresolved_task',title:'Renal function test still pending',detail:'Open for 12 days · Assigned to Nurse Alice',level:'Follow-up',sourceEntryId:'e-aug13',sourceVersionId:'e-aug13-v1',startOffset:0,endOffset:renalText.indexOf('.')+1,sourceExcerpt:'Renal function laboratory follow-up remains pending.',trust:'Clinician Confirmed',occurredAt:'Aug 13 · Nurse Follow-up',components:{risk:.45,unresolved:1,recency:.6,clinicalChange:.5,conflict:0,confirmation:1} },
  { id:'h-med',category:'medication_change',title:'Medication record corrected',detail:'Clinician clarified metformin was not stopped',level:'Follow-up',sourceEntryId:'e-aug24',sourceVersionId:'e-aug24-v2',startOffset:hbaText.indexOf('Sarah clarified'),endOffset:hbaText.indexOf('incomplete')+10,sourceExcerpt:'Sarah clarified she has continued metformin 500 mg twice daily; the earlier AI statement was incomplete',trust:'Clinician Confirmed',occurredAt:'Aug 24 · Doctor Consult',components:{risk:.45,unresolved:0,recency:.85,clinicalChange:.8,conflict:1,confirmation:1} },
];
const roles: Array<{role:Role; label:string; name:string}> = [{role:'clinician',label:'Clinician',name:'Dr Marcus Lim'},{role:'staff',label:'Staff',name:'Nurse Alice Wong'},{role:'patient',label:'Patient',name:'Sarah Tan'},{role:'admin',label:'Admin',name:'Clinic Admin'}];
const defaultWeights: Record<HighlightCategory, number> = {lab_abnormality:1.17,new_symptom:1.12,unresolved_task:1.08,medication_change:1.28,administrative:.84};

export default function Workspace() {
  const [role,setRole]=useState<Role>('clinician'); const [highlights,setHighlights]=useState(initialHighlights); const [weights,setWeights]=useState(defaultWeights);
  const [entries,setEntries]=useState(initialEntries); const [selectedSource,setSelectedSource]=useState<string>(); const [why,setWhy]=useState<string>(); const [filter,setFilter]=useState('All');
  const [notice,setNotice]=useState(''); const [drawer,setDrawer]=useState<'revision'|'collab'|'redaction'|null>(null); const [editing,setEditing]=useState(false); const [draft,setDraft]=useState(hbaText);
  const [comments,setComments]=useState([{id:'c1',author:'Nurse Alice Wong',body:'@clinician Could you confirm whether dizziness warrants an earlier review?',resolved:false},{id:'c2',author:'Dr Marcus Lim',body:'Reviewed. Keeping this open until the renal panel is back.',resolved:false}]);
  const [taskStatus,setTaskStatus]=useState('Open'); const refs=useRef<Record<string,HTMLElement|null>>({});
  const identity=roles.find((r)=>r.role===role)!; const patientMode=role==='patient';
  const ranked=useMemo(()=>rankHighlights(highlights,weights).slice(0,3),[highlights,weights]);
  const visibleEntries=entries.filter((e)=>!patientMode || (e.visibility==='patient'&&!e.ai)).filter((e)=>filter==='All'||(filter==='AI'&&e.ai)||(filter==='Clinical'&&!e.ai)||(filter==='Patient'&&e.type.includes('patient')));
  function feedback(item:Highlight,action:FeedbackAction){ if(patientMode)return; setWeights((w)=>updateClinicWeights(w,item.category,action)); setHighlights((all)=>all.map((h)=>h.id===item.id?{...h,pinned:action==='pin'?!h.pinned:h.pinned,status:action==='dismiss'?'dismissed':action==='accept'?'accepted':h.status}:h)); setNotice(action==='source_open'?'Source opened':action==='pin'?'Pinned and clinic preference updated':action==='dismiss'?'Dismissed; historical feedback retained':'Accepted as clinically relevant'); }
  function openSource(item:Highlight){ feedback(item,'source_open'); setSelectedSource(item.id); setTimeout(()=>refs.current[item.sourceEntryId]?.scrollIntoView({behavior:'smooth',block:'center'}),30); }
  function saveEdit(){ const target=entries.find((e)=>e.id==='e-aug24')!; const result=editEntry(target,target.versions.at(-1)!.version,draft,identity.name,new Date().toLocaleString()); setEntries((all)=>all.map((e)=>e.id===target.id?result.entry:e)); setEditing(false); setNotice('Treatment plan saved as a new immutable version'); setDrawer('revision'); }
  function doRevert(version:number){ const target=entries.find((e)=>e.id==='e-aug24')!; const result=revertEntry(target,version,identity.name,new Date().toLocaleString()); setEntries((all)=>all.map((e)=>e.id===target.id?result.entry:e)); setDraft(result.entry.content); setNotice(`Version ${result.entry.versions.at(-1)!.version} created from Version ${version}`); }
  const redaction=redactBeforeProvider('Sarah Tan · S1234567A · +65 9123 4567 · sarah.tan@example.com · DOB: 12/04/1972 · 18 Orchard Road');
  async function switchRole(next:Role){ const response=await fetch('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role:next})}); if(!response.ok){setNotice('Role switch rejected by server');return;} setRole(next); setNotice(`Server identity changed to ${next}`); }
  return <main className="app-shell">
    <header className="topbar"><Link className="brand" href="/"><span className="brand-mark">N</span><span>Nightingale <b>Care Note</b></span></Link><nav className="topnav"><a className="active" href="#workspace">Workspace</a><a href="#patients">Patients</a>{!patientMode&&<button onClick={()=>setDrawer('redaction')}>Security</button>}</nav><label className="role-switch"><span>Viewing as</span><strong>{identity.name} · {identity.label}</strong><select value={role} onChange={(e)=>void switchRole(e.target.value as Role)}>{roles.map((r)=><option value={r.role} key={r.role}>{r.name} · {r.label}</option>)}</select></label></header>
    <div className="workspace" id="workspace"><aside className="patient-rail" id="patients"><div className="rail-heading"><span>Clinic workspace</span><button>⌕</button></div><p className="clinic-name">Harbour Family Clinic</p><div className="patient-list">{[['ST','Sarah Tan','Review today · 10:30',''],['JL','Jason Lee','Follow-up · Aug 28','mint'],['MN','Mei Nordin','Review · Sep 02','sand'],['DK','Daniel Koh','Follow-up · Sep 04','rose'],['FA','Farah Aziz','Annual review · Sep 10','mint']].map((p,i)=><a className={`patient-row ${i===0?'selected':''}`} href="#sarah" key={p[1]}><span className={`avatar ${p[3]}`}>{p[0]}</span><span><strong>{p[1]}</strong><small>{p[2]}</small></span>{i===0&&<i>3</i>}</a>)}</div><div className="rail-footer"><span className="status-dot"/>All records synthetic</div></aside>
      <section className="patient-workspace" id="sarah"><header className="patient-header"><div><div className="eyebrow">Patients <span>/</span> Sarah Tan</div><div className="patient-title-row"><h1>Sarah Tan</h1><span className="patient-id">ST-2048</span></div><p>54 years · Type 2 diabetes · Hypertension</p></div>{!patientMode&&<div className="header-actions"><button className="quiet-button" onClick={()=>setDrawer('collab')}>Comments & tasks <b>3</b></button><button className="primary-button" onClick={()=>setEditing(true)}>Edit treatment plan</button></div>}</header>
        {patientMode?<section className="patient-summary"><span className="eyebrow">Patient summary</span><h2>Your care plan</h2><p>Your care team is reviewing recent dizziness and a change in your diabetes result. Please continue your medications as confirmed by Dr Lim and complete the requested kidney function blood test.</p><div><strong>Next step</strong><span>Complete renal blood test · Harbour Family Clinic</span></div></section>:<section className="glance"><div className="section-heading"><div><span className="eyebrow">10-second overview</span><h2>What matters now</h2></div><p>Updated 8:42 AM · exactly 3 priorities</p></div><div className="highlight-list">{ranked.map((h,i)=><article className={`highlight ${h.pinned?'is-pinned':''}`} key={h.id}><div className={`priority-number ${h.level==='Attention'?'amber':'blue'}`}>0{i+1}</div><div className="highlight-copy"><div className="highlight-labels"><span className={`severity ${h.level==='Attention'?'amber':'blue'}`}>{h.level}</span><span className={`trust ${h.trust==='AI Suggested'?'ai':''}`}>{h.status==='accepted'?'Accepted':h.trust}</span>{h.pinned&&<span className="pin-label">Pinned</span>}</div><h3>{h.title}</h3><p>{h.detail}</p><div className="source-line"><span>{h.occurredAt}</span><button onClick={()=>setWhy(why===h.id?undefined:h.id)}>Why this? {why===h.id?'↑':'↓'}</button></div>{why===h.id&&<div className="why-panel"><strong>Why this is prioritized</strong>{scoreReasons(h,weights[h.category]).map((r)=><span key={r}>• {r}</span>)}<small>Clinic weight {weights[h.category].toFixed(2)}× · bounded to 0.80–1.35</small></div>}</div><div className="highlight-actions"><button onClick={()=>openSource(h)}>Source</button><button onClick={()=>feedback(h,'accept')}>Accept</button><button onClick={()=>feedback(h,'dismiss')}>Dismiss</button><button className="pin" onClick={()=>feedback(h,'pin')} aria-label="Pin">{h.pinned?'◆':'◇'}</button></div></article>)}</div></section>}
        {!patientMode&&<section className="since-last"><div><span className="pulse"/><strong>Since last visit</strong></div><p><b>4 changes</b> · New AI session, dizziness reported, renal follow-up opened, medication conflict detected.</p><button onClick={()=>setFilter('AI')}>Review changes →</button></section>}
        <section className="timeline-preview"><div className="section-heading"><div><span className="eyebrow">Longitudinal care note</span><h2>{patientMode?'Your updates':'Timeline'}</h2></div>{!patientMode&&<div className="filters">{['All','AI','Tasks','Clinical','Patient'].map((f)=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div>}</div><div className="trend"><span>HbA1c</span><b>7.1</b><i/><b>7.3</b><i className="rise"/><b className="high">8.3 ↑</b><small>Apr 2025&nbsp;&nbsp;&nbsp; Feb 2026&nbsp;&nbsp;&nbsp; Aug 2026</small></div>{visibleEntries.map((entry)=><article className={`timeline-entry ${selectedSource&&initialHighlights.find((h)=>h.id===selectedSource)?.sourceEntryId===entry.id?'source-target':''}`} key={entry.id} ref={(node)=>{refs.current[entry.id]=node}}><time>{entry.date.split(',')[0]}<br/><span>{entry.date.includes(',')?entry.date.split(', ')[1]:''}</span></time><div className="timeline-line"><span/></div><div className="entry-card"><div className="entry-meta"><span className={`entry-type ${entry.ai?'ai-entry':''}`}>{entry.ai?'✦ ':''}{entry.label}</span><span>{entry.author} · {entry.time}</span>{entry.trust&&<span className={`confirmed ${entry.trust.includes('Conflict')?'conflict':''}`}>{entry.trust}</span>}{entry.decayTier&&<span className="decay">{entry.decayTier==='compressed'?'Compressed context':'Summary tier'}</span>}</div><h3>{entry.title}</h3><EntryContent entry={entry} highlight={initialHighlights.find((h)=>h.id===selectedSource&&h.sourceEntryId===entry.id)}/>{entry.supersededBy&&<div className="superseded"><b>Earlier AI memory preserved</b><span>Clinician correction on Aug 24 is authoritative. This entry has not been rewritten.</span></div>}<div className="entry-footer"><button>View full entry</button>{!patientMode&&!entry.ai&&<button onClick={()=>setDrawer('revision')}>Version {entry.versions.at(-1)?.version}</button>}<button onClick={()=>setDrawer('collab')}>{patientMode?'Instructions':'Comments'}</button></div></div></article>)}</section>
      </section></div>
    {notice&&<button className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></button>}
    {editing&&<div className="modal-backdrop"><section className="modal"><header><div><span className="eyebrow">Optimistic edit · Version {entries[0].versions.at(-1)!.version}</span><h2>Edit treatment plan</h2></div><button onClick={()=>setEditing(false)}>×</button></header><textarea value={draft} onChange={(e)=>setDraft(e.target.value)} rows={8}/><p className="form-help">A stale edit returns 409 instead of overwriting clinical content.</p><footer><button className="quiet-button" onClick={()=>setEditing(false)}>Cancel</button><button className="primary-button" onClick={saveEdit}>Save new version</button></footer></section></div>}
    {drawer&&<div className="drawer-backdrop" onClick={()=>setDrawer(null)}><aside className="drawer" onClick={(e)=>e.stopPropagation()}><header><div><span className="eyebrow">{drawer==='revision'?'Immutable audit':'Nightingale Care Note'}</span><h2>{drawer==='revision'?'Revision history':drawer==='collab'?'Comments & follow-up':'Pre-LLM redaction'}</h2></div><button onClick={()=>setDrawer(null)}>×</button></header>{drawer==='revision'&&<RevisionPanel entry={entries.find((e)=>e.id==='e-aug24')!} onRevert={doRevert}/>} {drawer==='collab'&&<CollabPanel comments={comments} setComments={setComments} status={taskStatus} setStatus={setTaskStatus} role={role}/>} {drawer==='redaction'&&<RedactionPanel before="Sarah Tan · S1234567A · +65 9123 4567 · sarah.tan@example.com · DOB: 12/04/1972 · 18 Orchard Road" after={redaction.redacted}/>}</aside></div>}
  </main>;
}

function EntryContent({entry,highlight}:{entry:CareEntry;highlight?:Highlight}){ if(!highlight)return <p>{entry.content}</p>; const v=entry.versions.find((x)=>x.id===highlight.sourceVersionId)!; return <p>{v.content.slice(0,highlight.startOffset)}<mark className="source-mark">{v.content.slice(highlight.startOffset,highlight.endOffset)}</mark>{v.content.slice(highlight.endOffset)}</p> }
function RevisionPanel({entry,onRevert}:{entry:CareEntry;onRevert:(v:number)=>void}){return <div className="revision-list">{[...entry.versions].reverse().map((v,i)=><article key={v.id} className={i===0?'current':''}><div><b>Version {v.version}{i===0?' · Current':''}</b><span>{v.actor} · {v.createdAt}</span></div>{v.revertedFrom&&<em>Restored from Version {v.revertedFrom}</em>}<p>{v.content}</p>{i>0&&<><div className="diff"><del>{v.content}</del><ins>{entry.versions.at(-1)!.content}</ins></div><button onClick={()=>onRevert(v.version)}>Restore as new version</button></>}</article>)}</div>}
function CollabPanel({comments,setComments,status,setStatus,role}:{comments:{id:string;author:string;body:string;resolved:boolean}[];setComments:React.Dispatch<React.SetStateAction<{id:string;author:string;body:string;resolved:boolean}[]>>;status:string;setStatus:(s:string)=>void;role:Role}){const [text,setText]=useState('');return <div className="collab"><section className="task-card"><span>Follow-up task</span><h3>Renal function laboratory follow-up</h3><p>Assigned to Nurse Alice · Open 12 days</p><select value={status} onChange={(e)=>setStatus(e.target.value)} disabled={role==='patient'}><option>Open</option><option>In Progress</option><option>Done</option></select></section><h3>Thread · {comments.filter((c)=>!c.resolved).length} open</h3>{comments.map((c)=><article className={c.resolved?'resolved':''} key={c.id}><b>{c.author}</b><p>{c.body}</p><button onClick={()=>setComments((all)=>all.map((x)=>x.id===c.id?{...x,resolved:!x.resolved}:x))}>{c.resolved?'Unresolve':'Resolve'}</button><button>Reply</button></article>)}{role!=='patient'&&<form onSubmit={(e)=>{e.preventDefault();if(!text.trim())return;setComments((all)=>[...all,{id:`c${Date.now()}`,author:role==='staff'?'Nurse Alice Wong':'Dr Marcus Lim',body:text,resolved:false}]);setText('')}}><textarea placeholder="Add a comment · use @clinician or @staff" value={text} onChange={(e)=>setText(e.target.value)}/><button className="primary-button">Comment</button></form>}</div>}
function RedactionPanel({before,after}:{before:string;after:string}){return <div className="redaction-demo"><p>Internal developer demonstration. Patients cannot access this surface.</p><span>BEFORE LLM</span><pre>{before}</pre><div className="redaction-arrow">↓ Redact before provider call</div><span>AFTER REDACTION</span><pre className="safe">{after}</pre><small>Name, ID, phone, email, address, and date of birth are removed before any provider invocation. Raw text is not written to audit logs.</small></div>}
