'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { rankHighlights } from '../lib/domain/importance';
import { redactBeforeProvider } from '../lib/domain/redaction';
import type { CareEntry, FeedbackAction, Highlight, HighlightCategory, Role } from '../lib/domain/models';

const SARAH_ID='20000000-0000-4000-8000-000000000001';
const SARAH_PLAN='30000000-0000-4000-8000-000000000005';
type Row=Record<string,unknown>;
type Patient={id:string;external_id:string;full_name:string;date_of_birth:string;summary:string;conditions:string[]};
type Comment={id:string;author:string;role:string;body:string;resolved:boolean;createdAt:string};
type Task={id:string;title:string;status:string;owner:string;createdAt:string};

const roles:Array<{role:Role;label:string;name:string}>=[
  {role:'clinician',label:'Clinician',name:'Dr Marcus Lim'},{role:'staff',label:'Staff',name:'Nurse Alice Wong'},
  {role:'patient',label:'Patient',name:'Sarah Tan'},{role:'admin',label:'Admin',name:'Clinic Admin'},
];
const portraits:Record<string,number>={'Sarah Tan':0,'Jason Lee':1,'Mei Nordin':2,'Daniel Koh':3,'Farah Aziz':4};
const defaultWeights:Record<HighlightCategory,number>={lab_abnormality:1.17,new_symptom:1.12,unresolved_task:1.08,medication_change:1.28,administrative:.84};

function nested(row:Row,key:string):Row|undefined{const value=row[key];return Array.isArray(value)?value[0] as Row|undefined:value as Row|undefined}
function date(value:unknown,time=false){const d=new Date(String(value));return Number.isNaN(d.valueOf())?'':d.toLocaleString('en-SG',time?{month:'short',day:'2-digit',hour:'numeric',minute:'2-digit'}:{month:'short',day:'2-digit',year:'numeric'})}
function age(value:string){return Math.max(0,2026-Number(value.slice(0,4)))}
function mapEntry(row:Row):CareEntry{
  const versions=((row.entry_versions as Row[]|undefined)??[]).sort((a,b)=>Number(a.version)-Number(b.version));
  const current=versions.find(v=>Number(v.version)===Number(row.current_version))??versions.at(-1)??{};const author=nested(row,'author');const type=String(row.entry_type??'clinical_note');
  const labels:Record<string,string>={doctor_consult:'Doctor Consult',nurse_followup:'Nurse Follow-up',ai_patient_session_summary:'AI Patient Session',ai_doctor_consult_summary:'AI Scribe · Doctor Consult'};
  return{id:String(row.id),type,label:labels[type]??type.replaceAll('_',' '),author:String(author?.full_name??(row.author_role==='system'?'Nightingale Scribe':'Care Team')),authorRole:String(author?.role??row.author_role??'system') as CareEntry['authorRole'],date:date(row.created_at),time:new Date(String(row.created_at)).toLocaleTimeString('en-SG',{hour:'numeric',minute:'2-digit'}),title:String(current.title??''),content:String(current.content??''),visibility:String(row.visibility) as CareEntry['visibility'],trust:row.trust_state as CareEntry['trust'],ai:type.startsWith('ai_'),decayTier:row.decay_tier as CareEntry['decayTier'],supersededBy:row.superseded_by?String(row.superseded_by):undefined,versions:versions.map(v=>({id:String(v.id),version:Number(v.version),content:String(v.content),actor:String(nested(v,'actor')?.full_name??'Care Team'),createdAt:date(v.created_at,true),revertedFrom:v.reverted_from_version?Number(v.reverted_from_version):undefined}))};
}
function mapHighlight(row:Row):Highlight|null{const span=((row.provenance_spans as Row[]|undefined)??[])[0];if(!span)return null;return{id:String(row.id),category:String(row.category) as HighlightCategory,title:String(row.title),detail:String(row.detail),level:String(row.severity) as Highlight['level'],sourceEntryId:String(span.source_entry_id),sourceVersionId:String(span.source_version_id),startOffset:Number(span.start_offset),endOffset:Number(span.end_offset),sourceExcerpt:String(span.source_excerpt),trust:String(row.trust_state) as Highlight['trust'],occurredAt:date(row.occurred_at,true),components:row.score_components as Highlight['components'],pinned:Boolean(row.pinned),status:String(row.status) as Highlight['status']}}
function mapComment(row:Row):Comment{const author=nested(row,'author');return{id:String(row.id),author:String(author?.full_name??'Care Team'),role:String(author?.role??'Care team'),body:String(row.body),resolved:Boolean(row.resolved),createdAt:date(row.created_at,true)}}
function mapTask(row:Row):Task{return{id:String(row.id),title:String(row.title),status:String(row.status),owner:String(nested(row,'owner')?.full_name??'Care team'),createdAt:date(row.created_at)}}
async function data(response:Response):Promise<Row>{return await response.json().catch(()=>({})) as Row}
async function error(response:Response,fallback:string){const body=await data(response);return String(body.error??fallback)}
function stateClass(value?:string){return(value??'unverified').toLowerCase().replaceAll(' ','-')}
function signals(h:Highlight){const list:string[]=[];if(h.components.recency>=.7)list.push('Recent');if(h.components.unresolved>=.6)list.push('Unresolved');if(h.category==='medication_change'||h.components.clinicalChange>=.8)list.push('Clinical change');if(h.components.conflict>0)list.push('Conflicting evidence');if(h.components.confirmation>0)list.push('Clinician confirmed');return list.slice(0,4)}

export default function Workspace({patientId}:{patientId:string}){
  const router=useRouter();const [role,setRole]=useState<Role>('clinician');const [patient,setPatient]=useState<Patient|null>(null);const [patients,setPatients]=useState<Patient[]>([]);
  const [highlights,setHighlights]=useState<Highlight[]>([]);const [weights,setWeights]=useState(defaultWeights);const [entries,setEntries]=useState<CareEntry[]>([]);const [comments,setComments]=useState<Comment[]>([]);const [tasks,setTasks]=useState<Task[]>([]);
  const [source,setSource]=useState<string>();const [why,setWhy]=useState<string>();const [filter,setFilter]=useState('All');const [notice,setNotice]=useState('');const [drawer,setDrawer]=useState<'revision'|'collab'|'redaction'|null>(null);const [editing,setEditing]=useState(false);const [draft,setDraft]=useState('');const [switching,setSwitching]=useState<Role|null>(null);const [loading,setLoading]=useState(true);const refs=useRef<Record<string,HTMLElement|null>>({});
  const identity=roles.find(item=>item.role===role)??roles[0];const patientMode=role==='patient',clinicianMode=role==='clinician',staffMode=role==='staff',adminMode=role==='admin';
  const ranked=useMemo(()=>rankHighlights(highlights,weights).filter(item=>item.status!=='dismissed').slice(0,3),[highlights,weights]);
  const visible=entries.filter(entry=>!patientMode||(entry.visibility==='patient'&&!entry.ai)).filter(entry=>filter==='All'||(filter==='AI'&&entry.ai)||(filter==='Clinical'&&!entry.ai)||(filter==='Patient'&&entry.visibility==='patient'));
  const treatment=entries.find(entry=>entry.id===SARAH_PLAN)??entries.find(entry=>entry.authorRole==='clinician');const followup=entries.find(entry=>entry.authorRole==='staff')??entries.at(-1);

  const load=useCallback(async()=>{const response=await fetch(`/api/workspace?patientId=${patientId}`,{cache:'no-store'});if(!response.ok)throw new Error(await error(response,'Care Note unavailable'));const body=await data(response);const p=body.patient as unknown as Patient;const next=(body.entries as Row[]).map(mapEntry);setPatient(p);setPatients((body.patients as unknown as Patient[])??[]);setRole((body.identity as Row).role as Role);setEntries(next);setHighlights((body.highlights as Row[]).map(mapHighlight).filter((item):item is Highlight=>Boolean(item)));setWeights({...defaultWeights,...body.weights as Record<HighlightCategory,number>});setComments((body.comments as Row[]).map(mapComment));setTasks((body.tasks as Row[]).map(mapTask));const plan=next.find(entry=>entry.id===SARAH_PLAN)??next.find(entry=>entry.authorRole==='clinician');if(plan)setDraft(plan.content);if(p.id!==patientId)router.replace(`/patients/${p.id}`)},[patientId,router]);
  useEffect(()=>{queueMicrotask(()=>{void(async()=>{try{let session=await fetch('/api/session',{cache:'no-store'});if(session.status===401)session=await fetch('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role:'clinician'})});if(!session.ok)throw new Error(await error(session,'Sign-in unavailable'));await load()}catch(reason){setNotice(reason instanceof Error?reason.message:'Care Note unavailable')}finally{setLoading(false)}})()})},[load]);

  async function switchRole(next:Role){setSwitching(next);setNotice('');try{const response=await fetch('/api/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role:next})});if(!response.ok)throw new Error(await error(response,'Unable to change viewing role'));if(next==='patient'&&patientId!==SARAH_ID)router.push(`/patients/${SARAH_ID}`);else await load();const selected=roles.find(item=>item.role===next)!;setNotice(`Viewing as ${selected.name} · ${selected.label}`)}catch(reason){setNotice(reason instanceof Error?reason.message:'Unable to change viewing role')}finally{setSwitching(null)}}
  async function feedback(item:Highlight,action:FeedbackAction){if(!clinicianMode)return;const response=await fetch('/api/importance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({highlightId:item.id,action})});if(!response.ok){setNotice(await error(response,'Feedback could not be saved'));return}const body=await data(response);const state=body.feedback as{pinned?:boolean;status?:Highlight['status']}|undefined;setWeights({...defaultWeights,...body.weights as Record<HighlightCategory,number>});setHighlights(all=>all.map(h=>h.id===item.id?{...h,pinned:state?.pinned??h.pinned,status:state?.status??h.status}:h));if(action!=='source_open')setNotice(action==='pin'?'Priority pinned':action==='dismiss'?'Suggestion dismissed and retained in history':'Priority accepted')}
  function openSource(item:Highlight){setSource(item.id);setWhy(undefined);window.setTimeout(()=>refs.current[item.sourceEntryId]?.scrollIntoView({behavior:'smooth',block:'center'}),60);window.setTimeout(()=>setSource(current=>current===item.id?undefined:current),4200);if(clinicianMode)void feedback(item,'source_open')}
  async function saveEdit(){if(!treatment)return;const expected=treatment.versions.at(-1)?.version;if(!expected)return;const response=await fetch(`/api/entries/${treatment.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({expectedVersion:expected,content:draft})});if(response.status===409){setNotice('This plan changed elsewhere. Reload before saving.');return}if(!response.ok){setNotice(await error(response,'Treatment plan could not be saved'));return}const body=await data(response);const next=mapEntry(body.entry as Row);setEntries(all=>all.map(entry=>entry.id===treatment.id?next:entry));setEditing(false);setNotice('Treatment plan saved as a new version');setDrawer('revision')}
  async function revert(version:number){const expected=treatment?.versions.at(-1)?.version;if(!treatment||!expected)return;const response=await fetch(`/api/entries/${treatment.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({expectedVersion:expected,revertFrom:version})});if(response.status===409){setNotice('This plan changed elsewhere. Reload before restoring.');return}if(!response.ok){setNotice(await error(response,'Version could not be restored'));return}const body=await data(response);const next=mapEntry(body.entry as Row);setEntries(all=>all.map(entry=>entry.id===treatment.id?next:entry));setDraft(next.content);setNotice(`Restored Version ${version} as a new version`)}
  async function addComment(body:string){if(!followup||!patient)return false;const response=await fetch('/api/comments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({entryId:followup.id,patientId:patient.id,body})});if(!response.ok){setNotice(await error(response,'Comment could not be saved'));return false}const result=await data(response);setComments(all=>[...all,mapComment(result.comment as Row)]);return true}
  async function toggleComment(id:string,resolved:boolean){const response=await fetch('/api/comments',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,resolved})});if(!response.ok){setNotice(await error(response,'Comment could not be updated'));return}setComments(all=>all.map(comment=>comment.id===id?{...comment,resolved}:comment))}
  async function taskStatus(id:string,status:string){const response=await fetch('/api/tasks',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id,status})});if(!response.ok){setNotice(await error(response,'Task could not be updated'));return}setTasks(all=>all.map(task=>task.id===id?{...task,status}:task))}
  const redaction=redactBeforeProvider('Sarah Tan · S1234567A · +65 9123 4567 · sarah.tan@example.com · DOB: 12/04/1972 · 18 Orchard Road');
  if(loading||!patient)return <main className="loading-screen"><span className="brand-mark">N</span><strong>Opening Care Note</strong><small>Connecting identity and patient context…</small></main>;
  const milestones=entries.slice().reverse().slice(-5);const lens=clinicianMode?'Priorities, trust, and evidence first':staffMode?'Open actions and follow-up first':patientMode?'Instructions and next steps first':'Clinic context and oversight first';

  return <main className="app-shell"><header className="topbar"><Link className="brand" href="/patients"><span className="brand-mark">N</span><span>Nightingale</span></Link><nav className="topnav" aria-label="Primary"><Link href="/patients">Patients</Link><span className="active">Care Note</span>{(clinicianMode||adminMode)&&<button onClick={()=>setDrawer('redaction')}>Demo tools</button>}</nav><label className={`role-switch ${switching?'is-pending':''}`}><span>{switching?'Changing view…':'Viewing as'}</span><strong>{identity.name} · {identity.label}</strong><select value={role} disabled={Boolean(switching)} onChange={event=>void switchRole(event.target.value as Role)} aria-label="Change viewing role">{roles.map(item=><option key={item.role} value={item.role}>{item.name} · {item.label}</option>)}</select></label></header>
    <aside className="patient-rail" aria-label="Patient shortcuts"><Link className="rail-mark" href="/patients"><span className="brand-mark">N</span><b>Patient directory</b></Link><div className="patient-list">{patients.map(item=><Link className={`patient-row ${item.id===patient.id?'selected':''}`} href={`/patients/${item.id}`} key={item.id} aria-label={`Open ${item.full_name}`}><span className="portrait" style={{'--portrait-index':portraits[item.full_name]??0} as React.CSSProperties}/><span className="patient-row-copy"><strong>{item.full_name}</strong><small>{item.summary}</small></span>{item.id===patient.id&&<i>{ranked.length}</i>}</Link>)}</div><Link className="rail-all" href="/patients"><span>⌕</span><b>All patients</b></Link></aside>
    <section className="patient-workspace"><div className={`role-lens lens-${role}`}><span>{identity.label} lens</span><strong>{lens}</strong></div><header className="patient-header"><span className="portrait portrait-header" style={{'--portrait-index':portraits[patient.full_name]??0} as React.CSSProperties} role="img" aria-label={`${patient.full_name}, synthetic portrait`}/><div className="patient-identity"><div className="eyebrow"><Link href="/patients">Patients</Link><span>/</span><span>{patient.full_name}</span></div><h1>{patient.full_name}</h1><p>{patient.external_id} · {age(patient.date_of_birth)} years</p><div className="condition-list">{patient.conditions.map(condition=><em key={condition}>{condition}</em>)}</div></div><div className="header-actions">{!patientMode&&!adminMode&&<button className="quiet-button" onClick={()=>setDrawer('collab')}>Comments & follow-up <b>{comments.filter(c=>!c.resolved).length+tasks.filter(t=>t.status!=='Done').length}</b></button>}{clinicianMode&&treatment&&<button className="primary-button" onClick={()=>setEditing(true)}>Edit treatment plan</button>}{adminMode&&<button className="quiet-button" onClick={()=>setDrawer('revision')}>Review history</button>}</div></header>
    <nav className="longitudinal-ribbon" aria-label="Longitudinal milestones"><span className="ribbon-label">Memory</span><div className="ribbon-track">{milestones.map((entry,index)=><button key={entry.id} onClick={()=>refs.current[entry.id]?.scrollIntoView({behavior:'smooth',block:'center'})} className={index===milestones.length-1?'current':''}><i/><span>{entry.date.replace(', 2026','').replace(', 2025',' ’25')}</span><strong>{entry.title}</strong></button>)}<span className="ribbon-line"/></div></nav>
    {patientMode?<PatientSummary patient={patient} tasks={tasks}/>:<div className="clinical-layout"><div className="clinical-main">{staffMode&&<ActionLens tasks={tasks} comments={comments} onOpen={()=>setDrawer('collab')}/>} {adminMode&&<AdminLens entries={entries} comments={comments} tasks={tasks}/>}<section className="glance"><div className="section-heading"><div><span className="eyebrow">10-second overview</span><h2>What matters now</h2></div><p>Exactly three current priorities</p></div><div className="highlight-list">{ranked.map((h,index)=><article className={`highlight trust-shape ${stateClass(h.trust)} ${h.pinned?'is-pinned':''} ${source===h.id?'evidence-origin':''}`} key={h.id}><div className={`priority-number ${h.level==='Attention'?'attention':'followup'}`}><small>0</small>{index+1}</div><div className="highlight-copy"><div className="highlight-labels"><span className="severity">{h.level}</span><span className="trust-state"><i/>{h.status==='accepted'?'Clinician Accepted':h.trust}</span>{h.pinned&&<span className="pin-label">Pinned</span>}</div><h3>{h.title}</h3><p>{h.detail}</p><div className="highlight-meta"><span>{h.occurredAt}</span><button aria-expanded={why===h.id} onClick={()=>setWhy(why===h.id?undefined:h.id)}>Why this? <span>{why===h.id?'−':'+'}</span></button></div>{why===h.id&&<div className="attention-lens"><strong>Attention lens</strong><div>{signals(h).map(signal=><span key={signal}>{signal}</span>)}</div><p>These signals explain why this needs attention now. Clinical judgment remains authoritative.</p></div>}</div><div className="highlight-actions"><button className="source-button" onClick={()=>openSource(h)}>↳ Evidence</button>{clinicianMode&&<><button onClick={()=>void feedback(h,'accept')}>Accept</button><button onClick={()=>void feedback(h,'dismiss')}>Dismiss</button><button className="pin" onClick={()=>void feedback(h,'pin')} aria-label={h.pinned?'Unpin priority':'Pin priority'}>{h.pinned?'◆':'◇'}</button></>}</div></article>)}</div></section><section className="since-last"><div><span className="pulse"/><strong>Since last visit</strong></div><p><b>{Math.min(4,entries.length)} updates</b> · {entries.slice(0,3).map(entry=>entry.title.toLowerCase()).join(', ')}.</p><button onClick={()=>refs.current[entries[0]?.id]?.scrollIntoView({behavior:'smooth'})}>Review updates →</button></section></div><aside className="context-rail"><ContextRail tasks={tasks} comments={comments} onOpen={()=>setDrawer('collab')}/></aside></div>}
    <section className="timeline-preview"><div className="section-heading"><div><span className="eyebrow">Longitudinal Care Note</span><h2>{patientMode?'Your updates':'Timeline'}</h2></div>{!patientMode&&<div className="filters">{['All','AI','Clinical','Patient'].map(item=><button className={filter===item?'active':''} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div>}</div>{patient.full_name==='Sarah Tan'&&<div className="trend"><span>HbA1c trend</span><b>7.1</b><i/><b>7.3</b><i/><b className="high">8.3 ↑</b><small>Apr 2025 → Aug 2026</small></div>}<div className="timeline-list">{visible.map(entry=>{const selected=highlights.find(h=>h.id===source&&h.sourceEntryId===entry.id);return <article className={`timeline-entry ${selected?'source-target':''}`} key={entry.id} ref={node=>{refs.current[entry.id]=node}}><time>{entry.date.split(',')[0]}<span>{entry.date.includes(',')?entry.date.split(', ')[1]:''}</span></time><div className="timeline-line"><span/></div><div className={`entry-card trust-shape ${stateClass(entry.trust)} ${entry.supersededBy?'superseded-state':''}`}><div className="entry-meta"><span className="entry-type">{entry.ai?'✦ ':''}{entry.label}</span><span>{entry.author} · {entry.time}</span>{entry.trust&&<span className="trust-state"><i/>{entry.trust}</span>}{entry.decayTier&&<span className="decay">{entry.decayTier==='compressed'?'Compressed context':entry.decayTier==='summary'?'Summary context':'Full context'}</span>}</div><h3>{entry.title}</h3><EntryContent entry={entry} highlight={selected}/>{entry.supersededBy&&<div className="superseded"><b>Earlier memory preserved</b><span>The clinician correction is authoritative; this source remains available for review.</span></div>}<div className="entry-footer">{!patientMode&&!entry.ai&&<button onClick={()=>setDrawer('revision')}>Version {entry.versions.at(-1)?.version}</button>}{!patientMode&&<button onClick={()=>setDrawer('collab')}>Comments</button>}</div></div></article>})}</div></section></section>
    {notice&&<button className="notice" onClick={()=>setNotice('')}>{notice}<span>×</span></button>}{editing&&treatment&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Version {treatment.versions.at(-1)?.version}</span><h2>Edit treatment plan</h2></div><button onClick={()=>setEditing(false)} aria-label="Close">×</button></header><textarea value={draft} onChange={event=>setDraft(event.target.value)} rows={8}/><p className="form-help">Saving creates a new immutable version. Existing history is preserved.</p><footer><button className="quiet-button" onClick={()=>setEditing(false)}>Cancel</button><button className="primary-button" onClick={()=>void saveEdit()}>Save new version</button></footer></section></div>}
    {drawer&&<div className="drawer-backdrop" onClick={()=>setDrawer(null)}><aside className="drawer" onClick={event=>event.stopPropagation()} role="dialog" aria-modal="true"><header><div><span className="eyebrow">{drawer==='revision'?'Version history':drawer==='collab'?'Care collaboration':'Demo tool'}</span><h2>{drawer==='revision'?'Revision history':drawer==='collab'?'Comments & follow-up':'Pre-provider redaction'}</h2></div><button onClick={()=>setDrawer(null)} aria-label="Close">×</button></header>{drawer==='revision'&&treatment&&<RevisionPanel entry={treatment} onRevert={version=>void revert(version)}/>} {drawer==='collab'&&<CollabPanel comments={comments} tasks={tasks} role={role} onAdd={addComment} onToggle={(id,resolved)=>void toggleComment(id,resolved)} onStatus={(id,status)=>void taskStatus(id,status)}/>} {drawer==='redaction'&&<RedactionPanel before="Sarah Tan · S1234567A · +65 9123 4567 · sarah.tan@example.com · DOB: 12/04/1972 · 18 Orchard Road" after={redaction.redacted}/>}</aside></div>}</main>;
}

function PatientSummary({patient,tasks}:{patient:Patient;tasks:Task[]}){return <section className="patient-summary"><div><span className="eyebrow">Your Care Note</span><h2>What to know today</h2><p>Your care team has organized the record around clear next steps and information you can safely act on.</p></div><div className="patient-next"><strong>Next steps</strong>{tasks.length?tasks.map(task=><span key={task.id}><i/> {task.title} · {task.status}</span>):<span><i/> Continue the care plan discussed with your clinical team.</span>}</div><div className="patient-instructions"><strong>Your current care</strong><p>{patient.summary}. Continue medications as confirmed by your clinician and contact the clinic if symptoms change.</p></div></section>}
function ActionLens({tasks,comments,onOpen}:{tasks:Task[];comments:Comment[];onOpen:()=>void}){const count=tasks.filter(task=>task.status!=='Done').length;return <section className="action-lens"><div><span className="eyebrow">Staff action lens</span><h2>{count} open follow-up {count===1?'action':'actions'}</h2><p>{comments.filter(comment=>!comment.resolved).length} open care-team comments need continuity.</p></div><button className="quiet-button" onClick={onOpen}>Open worklist</button></section>}
function AdminLens({entries,comments,tasks}:{entries:CareEntry[];comments:Comment[];tasks:Task[]}){return <section className="admin-lens"><span className="eyebrow">Clinic oversight</span><div><article><strong>{entries.length}</strong><span>care entries</span></article><article><strong>{tasks.filter(task=>task.status!=='Done').length}</strong><span>open follow-ups</span></article><article><strong>{comments.filter(comment=>!comment.resolved).length}</strong><span>open threads</span></article><article><strong>{entries.reduce((sum,entry)=>sum+entry.versions.length,0)}</strong><span>preserved versions</span></article></div></section>}
function ContextRail({tasks,comments,onOpen}:{tasks:Task[];comments:Comment[];onOpen:()=>void}){const task=tasks[0];return <><section><span className="eyebrow">Open follow-up</span>{task?<><h3>{task.title}</h3><p>{task.owner} · {task.status}</p></>:<p>No open follow-up.</p>}</section><section><span className="eyebrow">Care-team thread</span><strong>{comments.filter(comment=>!comment.resolved).length} open</strong><p>{comments.find(comment=>!comment.resolved)?.body??'No open care-team comments.'}</p><button onClick={onOpen}>Open collaboration →</button></section></>}
function EntryContent({entry,highlight}:{entry:CareEntry;highlight?:Highlight}){if(!highlight)return <p>{entry.content}</p>;const version=entry.versions.find(item=>item.id===highlight.sourceVersionId);if(!version)return <p>{entry.content}</p>;return <p>{version.content.slice(0,highlight.startOffset)}<mark className="source-mark">{version.content.slice(highlight.startOffset,highlight.endOffset)}</mark>{version.content.slice(highlight.endOffset)}</p>}
function RevisionPanel({entry,onRevert}:{entry:CareEntry;onRevert:(version:number)=>void}){return <div className="revision-list">{[...entry.versions].reverse().map((version,index)=><article key={version.id} className={index===0?'current':''}><div><b>Version {version.version}{index===0?' · Current':''}</b><span>{version.actor} · {version.createdAt}</span></div>{version.revertedFrom&&<em>Restored from Version {version.revertedFrom}</em>}<p>{version.content}</p>{index>0&&<><div className="diff"><del>{version.content}</del><ins>{entry.versions.at(-1)!.content}</ins></div><button onClick={()=>onRevert(version.version)}>Restore as new version</button></>}</article>)}</div>}
function CollabPanel({comments,tasks,role,onAdd,onToggle,onStatus}:{comments:Comment[];tasks:Task[];role:Role;onAdd:(body:string)=>Promise<boolean>;onToggle:(id:string,resolved:boolean)=>void;onStatus:(id:string,status:string)=>void}){const [text,setText]=useState('');const input=useRef<HTMLTextAreaElement>(null);return <div className="collab">{tasks.map(task=><section className="task-card" key={task.id}><span>Follow-up task</span><h3>{task.title}</h3><p>{task.owner} · Added {task.createdAt}</p><select value={task.status} onChange={event=>onStatus(task.id,event.target.value)} disabled={role==='patient'||role==='admin'}><option>Open</option><option>In Progress</option><option>Done</option></select></section>)}<h3>Care-team thread · {comments.filter(comment=>!comment.resolved).length} open</h3>{comments.map(comment=><article className={comment.resolved?'resolved':''} key={comment.id}><header><span className="comment-avatar">{comment.author.split(' ').map(part=>part[0]).slice(0,2).join('')}</span><span><b>{comment.author}</b><small>{comment.role} · {comment.createdAt}</small></span></header><p>{comment.body}</p>{role!=='patient'&&role!=='admin'&&<div><button onClick={()=>onToggle(comment.id,!comment.resolved)}>{comment.resolved?'Unresolve':'Resolve'}</button><button onClick={()=>{setText(`@${comment.author.split(' ')[0]} `);window.setTimeout(()=>input.current?.focus(),0)}}>Reply</button></div>}</article>)}{role!=='patient'&&role!=='admin'&&<form onSubmit={event=>{event.preventDefault();if(!text.trim())return;void onAdd(text).then(saved=>{if(saved)setText('')})}}><textarea ref={input} placeholder="Add a care-team comment" value={text} onChange={event=>setText(event.target.value)}/><button className="primary-button">Comment</button></form>}</div>}
function RedactionPanel({before,after}:{before:string;after:string}){return <div className="redaction-demo"><p>This demonstration shows the boundary applied before any optional external processing.</p><span>Original synthetic text</span><pre>{before}</pre><div className="redaction-arrow">↓ Remove identifying fields</div><span>Protected text</span><pre className="safe">{after}</pre><small>Name, ID, phone, email, address, and date of birth are removed before processing. Note bodies are never placed in activity logs.</small></div>}
