import { integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const clinics = sqliteTable('clinics', { id: text('id').primaryKey(), name: text('name').notNull() });
export const profiles = sqliteTable('profiles', { id: text('id').primaryKey(), clinicId: text('clinic_id').notNull(), name: text('name').notNull(), role: text('role').notNull(), patientId: text('patient_id') });
export const patients = sqliteTable('patients', { id: text('id').primaryKey(), clinicId: text('clinic_id').notNull(), name: text('name').notNull(), dateOfBirth: text('date_of_birth').notNull(), summary: text('summary').notNull() });
export const careEntries = sqliteTable('care_entries', { id: text('id').primaryKey(), clinicId: text('clinic_id').notNull(), patientId: text('patient_id').notNull(), authorRole: text('author_role').notNull(), authorId: text('author_id').notNull(), entryType: text('entry_type').notNull(), visibility: text('visibility').notNull(), currentVersion: integer('current_version').notNull().default(1), trustState: text('trust_state'), createdAt: text('created_at').notNull(), updatedAt: text('updated_at').notNull() });
export const entryVersions = sqliteTable('entry_versions', { id: text('id').primaryKey(), entryId: text('entry_id').notNull(), version: integer('version').notNull(), title: text('title').notNull(), content: text('content').notNull(), actorId: text('actor_id').notNull(), revertedFrom: integer('reverted_from'), createdAt: text('created_at').notNull() }, (t) => [uniqueIndex('idx_entry_versions_entry_version').on(t.entryId, t.version)]);
export const comments = sqliteTable('comments', { id: text('id').primaryKey(), entryId: text('entry_id').notNull(), parentId: text('parent_id'), authorId: text('author_id').notNull(), body: text('body').notNull(), resolved: integer('resolved', { mode: 'boolean' }).notNull().default(false), createdAt: text('created_at').notNull() });
export const tasks = sqliteTable('tasks', { id: text('id').primaryKey(), patientId: text('patient_id').notNull(), sourceEntryId: text('source_entry_id'), title: text('title').notNull(), ownerId: text('owner_id').notNull(), status: text('status').notNull(), createdAt: text('created_at').notNull() });
export const highlights = sqliteTable('highlights', { id: text('id').primaryKey(), patientId: text('patient_id').notNull(), category: text('category').notNull(), title: text('title').notNull(), detail: text('detail').notNull(), severity: text('severity').notNull(), status: text('status').notNull(), pinned: integer('pinned', { mode: 'boolean' }).notNull().default(false), baseScore: real('base_score').notNull(), createdAt: text('created_at').notNull() });
export const provenanceSpans = sqliteTable('provenance_spans', { id: text('id').primaryKey(), highlightId: text('highlight_id').notNull(), sourceEntryId: text('source_entry_id').notNull(), sourceVersionId: text('source_version_id').notNull(), startOffset: integer('start_offset').notNull(), endOffset: integer('end_offset').notNull(), sourceExcerpt: text('source_excerpt').notNull(), sourceHash: text('source_hash').notNull(), createdAt: text('created_at').notNull() });
export const aiScribedNotes = sqliteTable('ai_scribed_notes', { careEntryId: text('care_entry_id').primaryKey(), interactionType: text('interaction_type').notNull(), provider: text('provider').notNull(), model: text('model').notNull(), promptVersion: text('prompt_version').notNull(), redactionEventId: text('redaction_event_id').notNull(), sourceSessionId: text('source_session_id').notNull(), createdAt: text('created_at').notNull() });
export const importanceFeedback = sqliteTable('importance_feedback', { id: text('id').primaryKey(), clinicId: text('clinic_id').notNull(), highlightId: text('highlight_id').notNull(), actorId: text('actor_id').notNull(), category: text('category').notNull(), action: text('action').notNull(), signal: integer('signal').notNull(), createdAt: text('created_at').notNull() });
export const clinicImportanceWeights = sqliteTable('clinic_importance_weights', { clinicId: text('clinic_id').notNull(), category: text('category').notNull(), multiplier: real('multiplier').notNull().default(1), updatedAt: text('updated_at').notNull() }, (t) => [uniqueIndex('idx_clinic_category').on(t.clinicId, t.category)]);
export const auditLogs = sqliteTable('audit_logs', { id: text('id').primaryKey(), clinicId: text('clinic_id').notNull(), actorId: text('actor_id').notNull(), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), fromVersion: integer('from_version'), toVersion: integer('to_version'), createdAt: text('created_at').notNull() });
export const redactionEvents = sqliteTable('redaction_events', { id: text('id').primaryKey(), categories: text('categories').notNull(), provider: text('provider').notNull(), createdAt: text('created_at').notNull() });
